---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}
  annotations:
    helm.sh/hook: "post-install"
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: "hook-succeeded"
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.infra.mongodb.image }}
        resources:
{{ toYaml .Values.infra.mongodb.resources | indent 10 }}
        command:
        - /bin/bash
        - -c
        - |
          # Ждем пока MongoDB станет доступен
          until mongosh --host mongodb --eval "print(\"waited for connection\")"
          do
            echo "Waiting for MongoDB..."
            sleep 2
          done
          
          echo "MongoDB is ready, creating user..."
          
          # Создаем пользователя reports
          mongosh mongodb://admin:password@mongodb:27017/admin <<EOF
          use sausage-store
          db.createUser({
            user: "reports",
            pwd: "reportspassword", 
            roles: [
              { role: "readWrite", db: "sausage-store" }
            ]
          })
          EOF
          
          echo "User 'reports' created successfully!"
