apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  annotations:
    helm.sh/hook-weight: "-10"
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13
          envFrom:
            - configMapRef:
                name: postgresql-conf
          ports:
            - containerPort: {{ .Values.infra.postgresql.containerPort }}
          resources:
{{ toYaml .Values.infra.postgresql.resources | indent 12 }}
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.infra.postgresql.env.POSTGRES_USER }} -d {{ .Values.infra.postgresql.env.POSTGRES_DB }}
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.infra.postgresql.env.POSTGRES_USER }} -d {{ .Values.infra.postgresql.env.POSTGRES_DB }}
            initialDelaySeconds: 45
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
spec:
  ports:
    - port: {{ .Values.infra.postgresql.containerPort }}
      targetPort: {{ .Values.infra.postgresql.containerPort }}
  selector:
    app: postgresql
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-conf
data:
  POSTGRES_DB: {{ .Values.infra.postgresql.env.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.infra.postgresql.env.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.infra.postgresql.env.POSTGRES_PASSWORD }}
  PGDATA: {{ .Values.infra.postgresql.env.PGDATA }}
