---
apiVersion: v1
kind Service
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}
