name: Sausage Store Deploy

on:
  push:
    branches:
      - main

env:
  NEXUS_HELM_REPO: ${{ secrets.NEXUS_HELM_REPO }}
  NEXUS_HELM_REPO_USER: ${{ secrets.NEXUS_HELM_REPO_USER }}
  NEXUS_HELM_REPO_PASSWORD: ${{ secrets.NEXUS_HELM_REPO_PASSWORD }}
  SAUSAGE_STORE_NAMESPACE: ${{ secrets.NS }}
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Push Backend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKER_USER }}/sausage-backend:latest
          build-args: |
            VERSION=${{ github.sha }}
            
      - name: Push Frontend to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKER_USER }}/sausage-frontend:latest
          
      - name: Push Backend-report to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: ./backend-report/
          push: true
          tags: ${{ secrets.DOCKER_USER }}/sausage-backend-report:latest

  add_helm_chart_to_nexus:
    name: Add Helm Chart To Nexus
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.10.0'
          
      - name: Package Helm Chart
        run: |
          helm package sausage-store-chart/ --version 0.1.0
          
      - name: Upload to Nexus
        run: |
          curl -u $NEXUS_HELM_REPO_USER:$NEXUS_HELM_REPO_PASSWORD \
            --upload-file sausage-store-0.1.0.tgz \
            $NEXUS_HELM_REPO/sausage-store-0.1.0.tgz

  deploy_helm_chart_to_kubernetes:
    name: Deploy Helm Chart To Kubernetes
    runs-on: ubuntu-latest
    needs: add_helm_chart_to_nexus
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.10.0'
          
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'
          
      - name: Setup kubeconfig
        run: |
          echo "$KUBE_CONFIG" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig
          
      - name: Add Helm repo and deploy
        run: |
          export KUBECONFIG=kubeconfig
          helm repo add nexus $NEXUS_HELM_REPO --username $NEXUS_HELM_REPO_USER --password $NEXUS_HELM_REPO_PASSWORD
          helm repo update
          helm upgrade --install sausage-store nexus/sausage-store \
            --version 0.1.0 \
            --namespace $SAUSAGE_STORE_NAMESPACE \
            --set backend.image=${{ secrets.DOCKER_USER }}/sausage-backend:latest \
            --set frontend.image=${{ secrets.DOCKER_USER }}/sausage-frontend:latest \
            --set backend-report.image=${{ secrets.DOCKER_USER }}/sausage-backend-report:latest \
            --set frontend.ingress.host=front-yourname.2sem.students-projects.ru \
            --set global.vault.vaultToken=$VAULT_TOKEN
